/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/shared/BackButton.vue')['default']
    BaseModal: typeof import('./src/components/shared/modals/BaseModal.vue')['default']
    Button: typeof import('./src/components/shared/Button.vue')['default']
    CardImage: typeof import('./src/components/shared/CardImage.vue')['default']
    CardPicker: typeof import('./src/components/shared/CardPicker.vue')['default']
    CardsPicker: typeof import('./src/components/game/suggestion-wizard/shared/CardsPicker.vue')['default']
    ConfirmationModal: typeof import('./src/components/shared/modals/ConfirmationModal.vue')['default']
    copy: typeof import('./src/components/shared/PickCard copy.vue')['default']
    Flyout: typeof import('./src/components/shared/Flyout.vue')['default']
    GameMenu: typeof import('./src/components/shared/GameMenu.vue')['default']
    GamePlayTableRow: typeof import('./src/components/game/GamePlayTableRow.vue')['default']
    IconFluentEmojiFlatEyes: typeof import('~icons/fluent-emoji-flat/eyes')['default']
    IconHugeiconsView: typeof import('~icons/hugeicons/view')['default']
    IconIcBaselineClose: typeof import('~icons/ic/baseline-close')['default']
    IconIcBaselineDeleteForever: typeof import('~icons/ic/baseline-delete-forever')['default']
    IconIcBaselineEdit: typeof import('~icons/ic/baseline-edit')['default']
    IconIcons8Spy: typeof import('~icons/icons8/spy')['default']
    IconIcOutlineHideImage: typeof import('~icons/ic/outline-hide-image')['default']
    IconIcRoundClose: typeof import('~icons/ic/round-close')['default']
    IconIcRoundWarningAmber: typeof import('~icons/ic/round-warning-amber')['default']
    IconIcSharpManageSearch: typeof import('~icons/ic/sharp-manage-search')['default']
    IconIcSharpSettings: typeof import('~icons/ic/sharp-settings')['default']
    IconMaterialSymbolsArrowBackRounded: typeof import('~icons/material-symbols/arrow-back-rounded')['default']
    IconMaterialSymbolsArrowRightAltRounded: typeof import('~icons/material-symbols/arrow-right-alt-rounded')['default']
    IconMaterialSymbolsDeleteOutline: typeof import('~icons/material-symbols/delete-outline')['default']
    IconMaterialSymbolsDoNotDisturbOnRounded: typeof import('~icons/material-symbols/do-not-disturb-on-rounded')['default']
    IconMaterialSymbolsDoorOpenRounded: typeof import('~icons/material-symbols/door-open-rounded')['default']
    IconMaterialSymbolsWarningRounded: typeof import('~icons/material-symbols/warning-rounded')['default']
    IconMdiHideOutline: typeof import('~icons/mdi/hide-outline')['default']
    IconMdiPlay: typeof import('~icons/mdi/play')['default']
    IconMdiShowOutline: typeof import('~icons/mdi/show-outline')['default']
    IconOouiRedoLtr: typeof import('~icons/ooui/redo-ltr')['default']
    IconOouiUndoLtr: typeof import('~icons/ooui/undo-ltr')['default']
    IconSolarHamburgerMenuBold: typeof import('~icons/solar/hamburger-menu-bold')['default']
    IconSolarPenNewSquareBold: typeof import('~icons/solar/pen-new-square-bold')['default']
    IconSolarStarBold: typeof import('~icons/solar/star-bold')['default']
    InformationModal: typeof import('./src/components/shared/modals/InformationModal.vue')['default']
    LogoArea: typeof import('./src/components/shared/LogoArea.vue')['default']
    ModalContainer: typeof import('./src/components/ModalContainer.vue')['default']
    NotebookCell: typeof import('./src/components/game/NotebookCell.vue')['default']
    NotebookTable: typeof import('./src/components/game/NotebookTable.vue')['default']
    'PickCard copy': typeof import('./src/components/shared/PickCard copy.vue')['default']
    PlayerAvatar: typeof import('./src/components/shared/PlayerAvatar.vue')['default']
    PlayerInfo: typeof import('./src/components/game/PlayerInfo.vue')['default']
    PlayerPicker: typeof import('./src/components/game/suggestion-wizard/shared/PlayerPicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step1Asker: typeof import('./src/components/game/suggestion-wizard/Step1Asker.vue')['default']
    Step21Accusation: typeof import('./src/components/game/suggestion-wizard/Step21Accusation.vue')['default']
    Step2Hypothesis: typeof import('./src/components/game/suggestion-wizard/Step2Hypothesis.vue')['default']
    Step3Response: typeof import('./src/components/game/suggestion-wizard/Step3Response.vue')['default']
    Step4Reveal: typeof import('./src/components/game/suggestion-wizard/Step4Reveal.vue')['default']
    StepFooter: typeof import('./src/components/game/suggestion-wizard/shared/StepFooter.vue')['default']
    SuggestionWizard: typeof import('./src/components/game/SuggestionWizard.vue')['default']
    TermsModal: typeof import('./src/components/TermsModal.vue')['default']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
    Winner: typeof import('./src/components/game/Winner.vue')['default']
    WizardHeader: typeof import('./src/components/game/suggestion-wizard/shared/WizardHeader.vue')['default']
    WizardSlider: typeof import('./src/components/game/suggestion-wizard/shared/WizardSlider.vue')['default']
  }
}
