[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  force = true 
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"